### ISSUE TITLE
Flush 시 fsync()를 하지 않고 check_commit() 메커니즘으로 대체

### ISSUE THREAD

**Issue by ollybaysion** [ollybaysion/FSALSM#1]
### Task

- [x] Code Review (in LevelDB / Write 시)
    - [x] #2 
    - [x] #22
- [x] 실험
    - [x] #5 
    - [x] Minor Compaction File System 단계에서 로그 관찰
    - [x] 실험 - flush 시 fsync()로 인한 latency 저하 관찰 (Team Review 종료)
- [x] 구현
    - [x] #14
    - [x] #29

**Comment by ollybaysion** [comment]
## Minor Compaction File System 단계에서 로그 관찰
본 목적은 File System 단계에서 동작을 관찰하는 것이므로 다음 이슈들로 대체한다.
- #4 
- #18 
- #19

**Comment by ollybaysion** [comment]
## Direct I/O
DIO를 적용해본 결과, write 시 Block Size 단위로 요청을 보내야 한다는 문제점이 있다. 그렇게 하지 않을 경우 invalid argument 오류가 뜬다. WAL을 Block Size 단위로 write 하도록 코드를 바꾸는 Task를 TODO 상태로 추가하고 본 Task는 완료된 것으로 한다.

**Comment by ollybaysion** [comment]
## Task
- Direct I/O
- reqsync() 적용 시 문제점
- 다음 아이디어 (Delayed Compaction or Compaction Plugging) 구현
