### ISSUE TITLE
Immutable MemTable을 SSTable로 저장할 때 fsync() 대신 reqsync()으로 대체

### ISSUE THREAD

**Issue by ollybaysion** [ollybaysion/FSALSM#14]
## Task
- [x] BuildTable 함수에서 Sync()를 reqsync()으로 변경\
- [x] Benchmark 결과
- [x] 문제점 정리

**Comment by ollybaysion** [comment]
## Flush 시 File System
다음과 같은 File I/O 패턴을 보일 것이다.

```
- Create
- Write
- Write
- Write
- ...
- Request Metata Journaling (#19)
- Journaling Commit (kjournald2 / File System Recovery 가능)
- Checkpoint (Disk Synchronization 완료)
```

**Comment by ollybaysion** [comment]
## reqsync()
check_commit()이라는 시스템콜 이름은 놀랍도록 직관적이지 못하다. fsync()와 마찬가지로 -sync 형식을 유지하되 더 빠른 return이 이루어진다는 점을 고려하여 reqsync나 earlysync esync 등등으로 바꾸는 것이 어떨까 생각한다. 당장은 reqsync()가 가장 입에 붙는 것 같아 일단 reqsync()로 바꾼다.

**Comment by ollybaysion** [comment]
## 문제점 1. imm 삭제
imm를 바로 삭제하더라도 문제가 될 것은 없음. Crash가 발생하지 않는 상황에서는 어차피 page에 파일에 관한 내용들이 저장되어 있기 때문에 imm는 상관이 없고, crash가 발생한다면 WAL을 통한 Recovery가 이루어질 것이기 때문에 상관이 없음.

**Comment by ollybaysion** [comment]
## TODO
- [ ] 문제점 1. imm의 삭제
- [ ] 문제점 2. Crash Recovery
- [ ] 문제점 3. db_test 시 thread 관련 문제

**Comment by ollybaysion** [comment]
## Benchmark
Value Size를 256, 512, 1024, 2048, 4096B 바꾸어가며 측정 (fillrandom)
NobLSM에 비해 10% 정도의 성능 개선

**Comment by ollybaysion** [comment]
## TODO
문제점을 해결할 방법을 고민해야 한다. 다만, Benchmark 결과가 크게 달라지지 않을 것 같다. 왜냐하면 imm를 언제 삭제하고, GET 시에 shadowing 된 SSTable을 건너 뛰는 등의 매우 간단하게 이루어지는 작업들의 수정이기 때문이다. 따라서 본 Benchmark 결과를 토대로 다음 아이디어 구현에 들어갈 수 있을 것 같다.
