### ISSUE TITLE
LevelDB Write 흐름 정리

### ISSUE THREAD

**Issue by ollybaysion** [ollybaysion/FSALSM#2]
### Task

- [x] New (K,V) PUT
    - [x] DBImpl::Write 함수
- [x] Minor Compation
    - [x] DBImpl::CompactMemTable 함수
    - [x] DBImpl::WriteLevel0Table 함수
    - [x] BuildTable 함수 (db/builder.cc)

**Comment by ollybaysion** [comment]
#### DBImpl::Write() 함수 내부 
- MakeRoomForWrite() 함수
- BuildBatchGroup() 함수
- log_->AddRecord() 함수
- logfile_->Sync() 함수
- InsertInto() 함수 (memtable)

**Comment by ollybaysion** [comment]
#### DBImpl::CompactMemTable() 함수 내부
- WriteLevel0Table() 함수
- versions_->LogAndApply() 함수
- RemoveObsoleteFiles() 함수

**Comment by ollybaysion** [comment]
#### BuildTable() 함수 내부
- env->NewWritableFile() 함수
- builder = new TableBuilder()
- builder->Add(iter)
- builder->Finish()
- file->Sync()

**Comment by ollybaysion** [comment]
#### env_posix 시스템콜과 파일 시스템 단계에서의 고찰
- memcpy() 함수
- write() 함수
- FlushBuffer() 함수
- fdatasync() 함수

**Comment by ollybaysion** [comment]
- [ ] Iterator #3
- [ ] Table Builder #4

**Comment by ollybaysion** [comment]
#### Issue 종료
- [x] 모든 Task 수행
- [x] TODO 리스트 작성
