### ISSUE TITLE
Baseline {Kernel}

### ISSUE THREAD

**Issue by ollybaysion** [ollybaysion/FSALSM#24]
## Task
- [x] check_commit (reqsync) 시스템콜
- [x] is_committed 시스템콜
- [x] pending table / committed table

**Comment by ollybaysion** [comment]
Kernel에 대한 정리는 하나의 이슈로 묶어서 관리하는 것으로 하고 닫음
