### ISSUE TITLE
Baseline 구현 간 Writeback 이전 Committed Table로 옮겨가는 문제

### ISSUE THREAD

**Issue by ollybaysion** [ollybaysion/FSALSM#33]
## TODO
- [x] 1. iloc_mark_dirty 함수에서 ext4_writepages 함수로 해당 로직 이동
- [x] 2. 기존 Major Compaction 및 Minor Compaction에서 제대로 동작하는지 검증
- [ ] 3. 벤치마크 (db_bench / YCSB) 진행
- [ ] Writeback Latency 측정
