### ISSUE TITLE
Baseline: check_commit 방식 변경 및 Dependency Table 관리 방식 변경

### ISSUE THREAD

**Issue by ollybaysion** [ollybaysion/FSALSM#37]
## TODO
- [x] check_commit() 시스템콜
- [x] Data Writeback 완료 시 SSTable Commit
- [x] Dependency Table 큐로 변경
- [x] Major Compaction에 적용 및 db_bench 결과 분석
