### ISSUE TITLE
Disk Size 사용량 측정

### ISSUE THREAD

**Issue by ollybaysion** [ollybaysion/FSALSM#42]
## TODO
- [ ] SSTable Size 측정
- [ ] Total Disk Size
- [ ] Shadow Table Size
- [ ] Pending Table Size
- [ ] 실험 결과 분석
