### ISSUE TITLE
Code Review <Test>

### ISSUE THREAD

**Issue by ollybaysion** [ollybaysion/FSALSM#9]
## Task
- [ ] LevelDB가 제공하는 테스트 목록 정리
- [ ] 새로운 테스트 코드 추가 및 빌드
- [ ] leveldb_tests
    - [ ] autocompact_test
    - [ ] db_test
    - [ ] log_format_test

**Comment by ollybaysion** [comment]
#### 테스트의 종류
1. Smoke Test
- 가장 단순한 형태의 테스트 
2. White / Black-Box Test
- 단위 코드를 테스트 (코드 구현에 대한 지식이 있고 없고의 차이)
- 코드의 강점과 약점을 알 수 있음
3. Regression Test
- 시간이나 플랫폼에 따라 바뀌지 않는 빈번히 이루어지는 테스트
- 실패할 경우, 최근의 코드 변화를 확인
- 만드는데 더 많은 노력이 들어간다
4. Compliance Test
- 코딩 스탠다드에 부합하는지를 확인하는 테스트

**Comment by ollybaysion** [comment]
LevelDB가 제공하는 테스트를 파악하는 것은 우선순위가 당장 우선순위가 높지 않으므로 일단 닫음
